<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>SGCA_Sistema_Afonso_Pande_Igildo_Mufundo</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controlos\" />
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Database\cooperativa_agricola.sql" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MySql.Data">
      <HintPath>bin\Debug\net10.0-windows\MySql.Data.dll</HintPath>
    </Reference>
    <Reference Include="MySqlConnector">
      <HintPath>bin\Debug\net10.0-windows\MySqlConnector.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>